### ISSUE TITLE
Webtoon Screen과 관련된 스크롤 애니메이션을 구현한다.

### ISSUE THREAD

**Issue by JiminKim-dev** [JiminKim-dev/numble-naver-webtoon-clone#4]
## Description
React Native의 Animated를 사용하여 해당 기능들을 구현한다.

## Tasks
- [x]  최상단 스크롤시 헤더와 푸터가 보이지 않고, 스크롤시 보이게 한다.
    - [x]  스크롤이 발생하면 하단 푸터가 고정된다. 스크롤이 최상단에 위치하기 전까지 사라지지 않는다.
    - [ ]  스크롤 후 헤더가 완전히 고정되었으면 무료쿠키 툴팁이 생기고, 돋보기 아이콘 색이 검정으로 바뀐다. (필수 x)
- [x]  요일별 목록 화면을 구현한다.
    - [x]  스크롤 후 슬라이딩 된 헤더에 요일 탭이 고정된다.

### 참고 화면
![Screen_Recording_20230301_181158_Naver Webtoon](https://user-images.githubusercontent.com/85747667/224103613-0e7aee18-f8ed-4878-b4ad-f1a686838412.gif)
