### ISSUE TITLE
💄 웹툰과 관련된 UI 컴포넌트를 생성한다.

### ISSUE THREAD

**Issue by JiminKim-dev** [JiminKim-dev/numble-naver-webtoon-clone#6]
## Description
웹툰과 관련된 UI 컴포넌트를 생성한다.

[✏️ 노션 - UI 컴포넌트 분류하기](https://cypress-pink-680.notion.site/UI-fb5cabc6075f44739ad573a79d40b321)

## Task
- [x] 데이터와 관련된 types 생성
- [x] CardImage 컴포넌트 구현
- [x] Card 컴포넌트 구현
