### ISSUE TITLE
MyScreen과 DetailScreen의 컨텐츠 배치 및 기능 구현

### ISSUE THREAD

**Issue by JiminKim-dev** [JiminKim-dev/numble-naver-webtoon-clone#8]
## Descripton
- MyScreen에 컨텐츠를 배치한다.
- DetailScreen에 컨텐츠를 배치한다.

## Tasks
- [x] Myscreen의 알림 버튼을 누르면 아이콘이 변경된다.
- [x] DetailScreen의 스크롤이 아래로 내려가면 화살표 버튼이 활성화 된다.
    - [x] 화살표 버튼을 클릭하면 스크롤이 최상단으로 이동한다.
- [x] 관심 버튼을 클릭하면 관심버튼이 변경되고 알림버튼이 활성화된다. 비활성화시 반대
    - [x] 관심 버튼 클릭시 알림이 꺼져있으면 alert을 노출한다.
